/*
 * bootloader_config.h
 *
 *  Created on: 25.10.2016
 *      Author: ak
 */

#ifndef MCU_BOOTLOADERCONFIG_BOARD_BOOTLOADER_CONFIG_H_
#define MCU_BOOTLOADERCONFIG_BOARD_BOOTLOADER_CONFIG_H_

#define BOOTLOADER_BOOT_APP_USING_RESET 1

#define BOORLOADER_WAITTIME_FOR_APP_BOOT_ms 1000

#define BOOTLOADER_ALLOW_PAIN_TEXT_COMMUNICATION 0
#define BOOTLOADER_WITH_DECRYPT_SUPPORT 1



#endif /* MCU_BOOTLOADERCONFIG_BOARD_BOOTLOADER_CONFIG_H_ */
